[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
DOMAIN = "https://${{ RAILWAY_PUBLIC_DOMAIN }}"
DATABASE_URL = "${{ DATABASE_URL }}"
OPENAI_API_KEY = "${{ OPENAI_API_KEY }}" 